name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        dotnet-quality: 'preview'
    
    - name: Restore dependencies
      run: dotnet restore src/ReflectionMcp.csproj
    
    - name: Build
      run: dotnet build src/ReflectionMcp.csproj --configuration Release --no-restore
    
    - name: Run tests (if any)
      run: dotnet test src/ReflectionMcp.csproj --configuration Release --no-build --verbosity normal || true
